version: '2.3'
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'springboot_mysql_example'
      MYSQL_USER: 'newuser'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  spring-boot-api:
    image: spring-boot-api
    build:
      #Location of the Dockerfile
      context: ./api
      dockerfile: api.Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/springboot_mysql_example?autoReconnect=true&useSSL=false
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      - db
    volumes:
      - $HOME/.m2/repository:/root/.m2/repository
      - /data/spring-boot-api
  spring-boot-web:
    image: spring-boot-web
    build:
      context: ./web
      dockerfile: web.Dockerfile
    links:
      - spring-boot-api:spring-boot-api
    environment:
            API_HOST: http://spring-boot-api:8080
    depends_on:
      - spring-boot-api
    ports:
      - '3000:3000'
    expose:
      - '3000'
    volumes:
      - /data/spring-boot-web

volumes:
  my-db:
